loadstring(game:HttpGet("https://raw.githubusercontent.com/nvb201112/fast-attack-blox-fruits/refs/heads/main/attack3.luau"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/nvb201112/fast-attack-blox-fruits/refs/heads/main/aurafruit.luau"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/nvb201112/fast-attack-blox-fruits/refs/heads/main/m1nocd.luau"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/nvb201112/fast-attack-blox-fruits/refs/heads/main/tubolai.luau"))()
